### ISSUE TITLE
Switch ACF -> Cloud

### ISSUE THREAD

**Issue by FrankHeijden** [FrankHeijden/ServerUtils#10]

**Comment by bobhenl** [comment]
Weird is that when I don't execute any command, then there is peak too
https://timings.aikar.co/?id=15098fbb242645bca8d82df1d68d8760
![image](https://user-images.githubusercontent.com/18662086/111071416-678b9200-84d6-11eb-876c-be525d6bdeac.png)

**Comment by FrankHeijden** [comment]
It is a runnable, which always runs in the background. However, it should certainly not take that much % of the tick, which it also doesn't for most servers tbh (should be around 0.04% of the tick for most servers). Anyway, we're moving away from acf in the future in favour of cloud.
