### ISSUE TITLE
Datapack support

### ISSUE THREAD

**Issue by 4drian3d** [FrankHeijden/ServerUtils#19]
Since https://github.com/PaperMC/Paper/pull/5653 was incorporated in Paper, it might be a good idea that some function to handle datapacks could be added to the plugin. Since the function of ServerUtils is to handle plugins, which like datapacks, are server add-ons.

**Comment by FrankHeijden** [comment]
Not sure if it is really needed to include in ServerUtils, Minecraft has the [datapack command](https://minecraft.fandom.com/wiki/Commands/datapack) built-in. What behaviour should ServerUtils add in comparison to this vanilla command?

**Comment by 4drian3d** [comment]
At the moment, I don't see any extra functionality that ServerUtils can give to datapacks that Minecraft Vanilla itself doesn't have. As I said before, ServerUtils had the ability to control plugins, and at that time I thought it would be a good idea to control datapacks since they have a similar function, but I don't see any feature that doesn't currently exist that can be added.

**Comment by FrankHeijden** [comment]
Alright! Closing this issue.
