### ISSUE TITLE
Add possibility to hide plugins from pl

### ISSUE THREAD

**Issue by lucian929** [FrankHeijden/ServerUtils#28]
Pretty simple, just a way to hide specific plugins from /pl output.

**Comment by FrankHeijden** [comment]
I am not sure if this is a good feature for ServerUtils. Why would you want someone to only partially see your plugin list?

**Comment by lucian929** [comment]
I ask this feature because it could be useful for owners to hide things like private plugins or Anticheats

**Comment by FrankHeijden** [comment]
If you have private plugins, and you think some people can't be trusted with that information, why would you give them the ability to see the plugins?

**Comment by lucian929** [comment]
I keep our plugins list open, as I don't see a point in fully hiding it. I just think it'd be nice to hide our Anticheat from public view

**Comment by FrankHeijden** [comment]
I will leave this open, might add it in the future.
