### ISSUE TITLE
Support installing plugins from spigot resources/bukkit dev

### ISSUE THREAD

**Issue by josephverburg** [FrankHeijden/ServerUtils#4]
Would be nice if you could easily search and download plugins using commands in game.

For spigot resources you could use: https://spiget.org/
And for dev.bukkit you could use: https://bukkit.gamepedia.com/ServerMods_API

**Comment by FrankHeijden** [comment]
Interesting concept! I think the idea is really nice, a nice text/chat based interface of the spigot/bukkit site: but it might be a bit out of the scope of this plugin. I also think it is a bit of a security matter: do you really _want_ to allow arbitrary plugins being downloaded and installed from the internet during runtime?

**Comment by FrankHeijden** [comment]
I will close this issue as I will probably not implement this in ServerUtils, I think it is too dangerous to allow arbitrary jar downloading & loading to happen from in-game commands.
