### ISSUE TITLE
Conflict with plugins that hook into Brigadier

### ISSUE THREAD

**Issue by Revxrsal** [FrankHeijden/ServerUtils#45]
Plugins that hook with Brigadier to display tooltips and client-side validation, such as [LuckPerms](https://luckperms.net/) and other custom plugins on our server (using commodore), no longer seem to get their tooltips working. When ServerUtils is removed, this feature works normally again.

**Comment by FrankHeijden** [comment]
Interesting, not quite sure what default behaviour ServerUtils has that would impact plugins using Commodore, but I will look into it in the coming week.

**Comment by FrankHeijden** [comment]
Looked into it a bit, it seems that the call to `CraftServer#syncCommands` in ServerUtils after the commandmap has been modified is causing this weird behaviour. Will investigate later for a possible solution.

**Comment by Revxrsal** [comment]
Yeah, that perhaps is the cause. The syncCommands dismisses any non-vanilla Brigadier data. 
Since commodore is the main framework that plugins use for hooking into brigadier, I believe it's possible to do [something like that](https://github.com/lucko/commodore/blob/master/src/main/java/me/lucko/commodore/CommodoreImpl.java#L286) to fix it. Of course this only fixes it on commodore hooks. I'm not perfectly sure if there are better solutions, though.

**Comment by FrankHeijden** [comment]
Yeah, I quickly looked earlier today at what exactly we need from syncCommands, and basically all we need in serverutils is to resend the commandmap to the player such that old commands will not be suggested to them. This can be done, but sadly the logic for that is nested in the syncCommands method. I will implement this somewhere this week as it requires a good look to get the methods right for 1.8 - 1.18.

**Comment by FrankHeijden** [comment]
Hey, could you verify this issue is fixed with PR #46 ?

**Comment by Revxrsal** [comment]
Yes, I can confirm that this fixes the bug!

![image](https://user-images.githubusercontent.com/26172484/156562592-aead74c9-e07f-4d19-8dae-3259a319df95.png)

Tested on 1.13.2. Thanks a lot.

**Comment by FrankHeijden** [comment]
Great! Not releasing 4.3.2 now, also want to check paper compatibility with 1.18.2 as soon as they release
